# Generated by Django 6.0.6 on 2026-06-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('temperatura_minima', models.FloatField()),
                ('temperatura_maxima', models.FloatField()),
                ('solo_ideal', models.CharField(max_length=100)),
                ('umidade_ideal', models.CharField(max_length=50)),
                ('epoca_plantio', models.CharField(max_length=100)),
                ('tempo_colheita_dias', models.IntegerField()),
                ('dificuldade', models.CharField(max_length=50)),
            ],
        ),
    ]
